#!/usr/bin/python
import sys
import os
import os.path
import argparse
import shlex
from subprocess import Popen, PIPE

benches = [
    ##'600.perlbench_s', # cannot run instrument because of integer overflow
    ##'602.gcc_s',      # compile issue
    #'605.mcf_s',
    ##'607.cactuBSSN_s',# compile issue
    #'619.lbm_s',
    #'620.omnetpp_s',
    #'623.xalancbmk_s',
    #'625.x264_s',
    #'631.deepsjeng_s',
    #'638.imagick_s',
    #'641.leela_s',
    #'644.nab_s',
    #'657.xz_s',
    #'998.specrand_is',
    '100.test',
    ]

cmd_options = {
        '600.perlbench_s':
        '-I%s/600.perlbench_s/lib %s/600.perlbench_s/checkspam.pl 2500 5 25 11 150 1 1 1 1' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '602.gcc_s':
        '%s/602.gcc_s/gcc-pp.c -O5 -fipa-pta -o %s/602.gcc_s/gcc-pp.opts-O5_-fipa-pta.s' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '605.mcf_s':
        '%s/605.mcf_s/inp.in' % (os.getenv('CPU2017_RUN_DIR')),
        '607.cactuBSSN_s':
        '%s/607.cactuBSSN_s/spec_ref.par'  % (os.getenv('CPU2017_RUN_DIR')),
        '619.lbm_s':
        '2000 %s/619.lbm_s/reference.dat 0 0 %s/619.lbm_s/200_200_260_ldc.of' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '620.omnetpp_s':
        '-c General -r 0',
        '623.xalancbmk_s':
        '-v %s/623.xalancbmk_s/t5.xml %s/623.xalancbmk_s/xalanc.xsl' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '625.x264_s':
        '--seek 500 --dumpyuv 200 --frames 1250 -o %s/625.x264_s/BuckBunny_New.264 %s/625.x264_s/BuckBunny.yuv 1280x720' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '631.deepsjeng_s':
        '%s/631.deepsjeng_s/ref.txt' % (os.getenv('CPU2017_RUN_DIR')),
        '638.imagick_s':
        '-limit disk 0 %s/638.imagick_s/refspeed_input.tga -resize 817%% -rotate -2.76 -shave 540x375 -alpha remove -auto-level -contrast-stretch 1x1%% -colorspace Lab -channel R -equalize +channel -colorspace sRGB -define histogram:unique-colors=false -adaptive-blur 0x5 -despeckle -auto-gamma -adaptive-sharpen 55 -enhance -brightness-contrast 10x10 -resize 30%% %s/638.imagick_s/refspeed_output.tga' % (os.getenv('CPU2017_RUN_DIR'), os.getenv('CPU2017_RUN_DIR')),
        '641.leela_s':
        '%s/641.leela_s/ref.sgf' % (os.getenv('CPU2017_RUN_DIR')),
        '644.nab_s':
        '%s/644.nab_s/3j1n 20140317 220' % (os.getenv('CPU2017_RUN_DIR')),
        '657.xz_s': '%s/cpu2006docs.tar.xz 6643 055ce243071129412e9dd0b3b69a21654033a9b723d874b2015c774fac1553d9713be561ca86f74e4f16f22e664fc17a79f30caa5ad2c04fbc447549c2810fae 1036078272 1111795472 4' % (os.getenv('CPU2017_RUN_DIR')),
        '998.specrand_is': '%s/1255432124 234923' % (os.getenv('CPU2017_RUN_DIR')),
        '100.test': '',
    }

def run_cmd(cmd, log=None, only_print=False):
    print(cmd)
    if only_print:
        return

    if log:
        output = open(log, 'w')
        process = Popen(shlex.split(cmd), stdout=output, stderr=output)
    else:
        #process = Popen(shlex.split(cmd), stdout=PIPE, stderr=PIPE)
        process = Popen(shlex.split(cmd))
    process.communicate()
    exit_code = process.wait()
    if (exit_code != 0):
        print('Execution Failed with error %d. See %s' % (exit_code, log))
        exit(1)

def run_build():
    makedirs(os.getenv('DCCE_RTLIB_BUILD_DIR'))
    run_cmd('%s/build.sh' % (os.getenv('DCCE_ROOT')))

def run_clean():
    run_cmd('rm -rf %s' % os.getenv('DCCE_RTLIB_BUILD_DIR'))
    run_cmd('bash %s/clean.sh' % (os.getenv('SVF_ROOT')))
    run_cmd('rm -rf %s/test.bc' % (os.getenv('ORG_BC_ROOT')))

def run_callgraph():
    makedirs(os.getenv('ORG_CG_DIR'))
    for bench in benches:
        run_cmd(cmd = 'wpa -ander -dump-callgraph %s/%s %s/%s.bc' \
                % (os.getenv('ORG_CG_DIR'), bench, os.getenv('ORG_BC_ROOT'), bench),
                log = '%s/%s.log' % (os.getenv('ORG_CG_DIR'), bench))

def run_ccenc(ccenc_dir):
    makedirs(ccenc_dir)
    for bench in benches:
        run_cmd(cmd = 'ccencoder/gen_calling_context %s/%s-final.cg ' \
                      '%s/%s.dot ' \
                      '%s/%s.cc ' \
                      '%s/%s.maxid ' \
                      '%s/%s.backedge ' \
                      '%s/%s.funcptr ' \
                      '%s/%s.maxneighbors ' \
                      '%s %s ' %
                      (os.getenv('ORG_CG_DIR'), bench,
                       ccenc_dir, bench,
                       ccenc_dir, bench,
                       ccenc_dir, bench,
                       ccenc_dir, bench,
                       ccenc_dir, bench,
                       ccenc_dir, bench,
                       bench, 'main'),
                 log = '%s/%s.log' % (ccenc_dir, bench))

def run_instrument(bc_dir, ccenc_dir, instr_method):
    makedirs(bc_dir)
    for bench in benches:
        bench_code = int(bench[:3])
        run_cmd(cmd = 'wpa -ander -ccinput %s/%s.cc -instr-method %s -bench-code %d -dump-modules %s %s/%s.bc' \
                    % (ccenc_dir, bench, instr_method, bench_code,
                       bc_dir,
                       os.getenv('ORG_BC_ROOT'), bench),
                log = '%s/%s.log' % (bc_dir, bench))

def run_make_exe(bin_dir, bc_dir, rtlib_dir):
    makedirs(bin_dir)
    for bench in benches:
        if bench == '100.test':
            run_cmd(cmd = 'bash %s/test.make.out %s %s %s %s' % \
                    (os.getenv('CPU2017_MAKE_DIR'),
                    bc_dir,
                    bin_dir,
                    rtlib_dir,
                    bench),
                    log = '%s/%s.log' % (bin_dir, bench))
        elif bench in ['620.omnetpp_s', '623.xalancbmk_s', '641.leela_s']:
            run_cmd(cmd = 'bash %s/common.clang++.make.out %s %s %s %s' % \
                    (os.getenv('CPU2017_MAKE_DIR'),
                    bc_dir,
                    bin_dir,
                    rtlib_dir,
                    bench),
                    log = '%s/%s.log' % (bin_dir, bench))
        else:
            run_cmd(cmd = 'bash %s/common.clang.make.out %s %s %s %s' % \
                    (os.getenv('CPU2017_MAKE_DIR'),
                    bc_dir,
                    bin_dir,
                    rtlib_dir,
                    bench),
                    log = '%s/%s.log' % (bin_dir, bench))

def run_bench_base():
    for run in range(2):
        base_stats_dir = '%s/%s' % (os.getenv('BASE_STATS_DIR'), run)
        makedirs(base_stats_dir)
        for bench in benches:
            cmd = '(time %s/%s %s) > %s/%s.log 2>&1' % \
                    (os.getenv('CPU2017_BIN_DIR'), bench, cmd_options[bench],
                     base_stats_dir, bench)
            print(cmd)
            #os.system(cmd)

def run_bench(stats_dir, bin_dir, num_tests):
    for run in range(num_tests):
        base_stats_dir = '%s/%s' % (stats_dir, run)
        makedirs(base_stats_dir)
        for bench in benches:
            cmd = '(time %s/%s %s) > %s/%s.log 2>&1' % \
                    (bin_dir, bench, cmd_options[bench],
                     base_stats_dir, bench)
            print(cmd)
            cmd = 'mv gmon.out %s/%s.gmon' % \
                    (base_stats_dir, bench)
            print(cmd)
            #os.system(cmd)


def main(args):

    if (args.build == False and \
            args.clean == False and \
            args.callgraph == False \
            and args.ccenc == None and \
            args.instrument == None and \
            args.make_exe == None and \
            args.run_bench == None):
        print("Nothing to do ...\nrun 'run_dcce -h' to see how to use.")
        exit(1)

    if (args.build):
        run_build()
    if (args.clean):
        run_clean()
    if (args.callgraph):
        run_callgraph()
    if (args.ccenc != None):
        if args.ccenc == 'dcce':
            run_ccenc(os.getenv('DCCE_CCENC_DIR'))
        elif args.ccenc == 'pcce':
            run_ccenc(os.getenv('PCCE_CCENC_DIR'))
    if (args.instrument != None):
        if args.instrument == 'base2':
            run_instrument(os.getenv('BASE2_BC_DIR'), os.getenv('DCCE_CCENC_DIR'), 'dcce')
        elif args.instrument == 'dcce':
            run_instrument(os.getenv('DCCE_BC_DIR'), os.getenv('DCCE_CCENC_DIR'), 'dcce')
        elif args.instrument == 'pcce':
            run_instrument(os.getenv('PCCE_BC_DIR'), os.getenv('PCCE_CCENC_DIR'), 'pcce')
    if (args.make_exe != None):
        if args.make_exe == 'base2':
            run_make_exe(os.getenv('BASE2_BIN_DIR'), os.getenv('BASE2_BC_DIR'), os.getenv('BASE2_RTLIB_DIR'))
        elif args.make_exe == 'dcce':
            run_make_exe(os.getenv('DCCE_BIN_DIR'), os.getenv('DCCE_BC_DIR'), os.getenv('DCCE_RTLIB_DIR'))
        elif args.make_exe == 'pcce':
            run_make_exe(os.getenv('PCCE_BIN_DIR'), os.getenv('PCCE_BC_DIR'), os.getenv('PCCE_RTLIB_DIR'))
    if (args.run_bench != None):
        if args.run_bench == 'base2':
            run_bench(os.getenv('BASE2_STATS_DIR'), os.getenv('BASE2_BIN_DIR'), 2)
        elif args.run_bench == 'dcce':
            run_bench(os.getenv('DCCE_STATS_DIR'), os.getenv('DCCE_BIN_DIR'), 2)
        elif args.run_bench == 'pcce':
            run_bench(os.getenv('PCCE_STATS_DIR'), os.getenv('PCCE_BIN_DIR'), 2)

def makedirs(dir):
    if not os.path.exists(dir):
        os.makedirs(dir)

if __name__== "__main__":
    if os.getenv('DCCE_ENV_SETUP') != 'YES':
        print("Environment Variabls are not set. run 'source %s' first." % 'setup_env.sh')
        exit(1)

    parser = argparse.ArgumentParser(\
            description='Main program to run DCCE project.')
    parser.add_argument('-build', action='store_true',
            help='build SVF and runtime.')
    parser.add_argument('-clean', action='store_true',
            help='clean all the output files.')
    parser.add_argument('-callgraph', action='store_true',
            help='run wpa to genrate callgph(.cg) file')
    parser.add_argument('-ccenc', choices=['dcce', 'pcce', 'valence'],
            help='run calling context encoding with given method.')
    parser.add_argument('-instrument', choices=['base2', 'dcce', 'pcce', 'valence'],
            help='run wpa to instrument benchmarks.')
    parser.add_argument('-make-exe', choices=['base2', 'dcce', 'pcce', 'valence'],
            help='make executable.')
    parser.add_argument('-run-bench', choices=['base', 'base2', 'dcce', 'pcce', 'valence'],
            help='run instrumented benchmarks.')
    args = parser.parse_args()

    main(args)
