#!/usr/bin/python3
import argparse
import logging
import os
import os.path
import pandas
import sys
import utils
from graphviz import Digraph
from callgraph import callgraph as callgraph
from callgraph import pccegraph as pccegraph
from dcce import dcce as dcce
from johnson import simple_cycles
import pcce

benches = [
    '100.test',
    '500.perlbench_r', # setjmp/longjmp
    #'502.gcc_r',       # Link error 
    '505.mcf_r',
    '520.omnetpp_r',   # Adopted indirect call promotion pass
    #'523.xalancbmk_r',
    '525.x264_r',
    '531.deepsjeng_r',
    '541.leela_r',
    #'548.exchange2_r'  # Fortran
    '557.xz_r',
    #'503.bwaves_r',    # Fortran
    #'507.cactuBSSN_r', # Link error
    '508.namd_r',
    #'510.parest_r',    # Compile error
    #'511.povray_r',
    '519.lbm_r',
    #'521.wrf_r',       # Fortran
    #'526.blender_r',   # setjmp/longjmp
    #'527.cam4_r',      # Fortran
    '538.imagick_r',
    '544.nab_r',
    #'549.fotonik3d_r', # Fortran
    #'554.roms_r',      # Fortran
    ]


class CGAnalyzer:
    def __init__(self, cg, bench, outdir):
        self.cg = cg
        self.bench = bench
        self.outdir = outdir
        self.cycles, self.scc_orig, self.scc = self.find_cycles()
        # cycle -> (entry edge, back edge)
        self.eb2c = self.find_backedges()

    def find_cycles(self):
        adj_list = {}
        for node in self.cg.nodes():
            adj_list[node] = []
            for neighbor, callsite in self.cg.neighbors(node):
                adj_list[node].append(neighbor)

        return simple_cycles(adj_list)



    #def find_cycles(self):
    #    # 0: not visited
    #    # 1: in stack
    #    # 2: done
    #    visited = {}
    #    for n in self.cg.nodes():
    #        visited[n] = 0
    #    cycles = []

    #    for n in self.cg.nodes():
    #        if visited[n] == 0:  # not visited
    #            stack = []
    #            stack.append(n)
    #            visited[n] = 1 # in stack
    #            logging.debug('processing %s' % n)
    #            self.process_dfs_tree(stack, visited, cycles)

    #    return cycles

    #def process_dfs_tree(self, stack, visited, cycles):
    #    for n, cs in self.cg.neighbors(stack[-1]):
    #        #logging.debug('next neighbor: %s' % n)
    #        if visited[n] == 1:  # not visited
    #            self.add_cycle(stack, n, cycles)
    #        elif visited[n] == 0:# in stack
    #            stack.append(n);
    #            visited[n] = 1;
    #            logging.debug('visiting %s' % n)
    #            self.process_dfs_tree(stack, visited, cycles)
    #    logging.debug('done %s' % stack[-1])
    #    visited[stack[-1]] = 2 # done
    #    stack.pop()

    #def add_cycle(self, stack, n, cycles):
    #    logging.debug('found cycle - %s' % n)
    #    logging.debug(stack)
    #    stack2 = []
    #    stack2.append(stack.pop())
    #    logging.debug(stack2)
    #    logging.debug(n)

    #    while stack2[-1] != n:
    #        stack2.append(stack.pop())

    #    cycle = []
    #    while stack2:
    #        cycle.append(stack2[-1])
    #        stack.append(stack2.pop())
    #    cycles.append(cycle)

    def find_backedges(self):
        eb2c = {}
        for cycle in self.cycles:
            logging.debug('find backes for cycle')
            logging.debug(cycle)
            for idx_n, node in enumerate(cycle):
                logging.debug('checking %s' % node)
                for incident, ics in self.cg.incidents(node):
                    if incident not in cycle:
                        logging.debug('      backedge %s %s' % (incident, ics))
                        backedges = self.get_edges(cycle[idx_n-1], node)
                        if ics not in eb2c:
                            eb2c[ics] = {}
                        for backedge in backedges:
                            if backedge not in eb2c[ics]:
                                eb2c[ics][backedge] = []
                            eb2c[ics][backedge].append(cycle)
        return eb2c


    def get_edges(self, fr, to):
        logging.debug('        getting edges from %s to %s' % (fr, to))
        edges = []
        for caller, (callee, callsite) in self.cg.edges():
            if caller == fr and callee == to:
                logging.debug('found edge %s %s %s' % (caller, callee, callsite))
                edges.append(callsite)
        return edges

    def get_stats(self):
        return [len(self.cg.nodes()), len(self.cg.edges()), len(self.scc_orig), len(self.cycles)]

    def write_cycles(self):
        outfile = '%s/%s.cycles' % (self.outdir, self.bench)
        f = open(outfile, 'w')
        f.write('printing cycles ...\n')
        for entryedge, b2c in self.eb2c.items():
            for backedge, cycles in b2c.items():
                for cycle in cycles:
                    f.write('[%s : %s]' % (entryedge, backedge))
                    for n in cycle:
                        f.write(n + ' ')
                    f.write('\n')
        f.write('printing scc_orig ...\n')
        for components in self.scc_orig:
            for n in components:
                f.write('%s ' % n)
            f.write('\n')
        f.write('printing scc ...\n')
        for components in self.scc:
            for n in components:
                f.write('%s ' % n)
            f.write('\n')
        f.close()

    def render_callgraph(self):
        dot = Digraph()
        for node in self.cg.nodes():
            dot.node(node, label=node)

        for caller, (callee, callsite) in self.cg.edges():
            wt = self.cg.edge_weight((caller,callee,callsite))
            dot.edge(caller, callee,
                    label=callsite+':'+str(wt))

        ## create dot file and render it
        outfile = '%s/%s.dot' % (self.outdir, self.bench)
        dot.save(outfile)
        dot.render(outfile, view=False)



def main(args):
    headers = ['#nodes', '#edges', '#SCC', '#cycles']
    data = []
    idx = []
    for bench in benches:
        logging.basicConfig(level=logging.DEBUG,  filename='%s/%s.log' % (args.outdir, bench), filemode='w') # , format='%s(names)s - %(levelname)s - %s(message)s')
        print('Analyzing %s' % bench)
        input_cg = '%s/%s-final.cg' % (os.getenv('ORG_CG_DIR'), bench)
        cg, node2id = utils.make_callgraph(input_cg, None, args.root)
        cga = CGAnalyzer(cg, bench, args.outdir)
        idx.append(bench)
        data.append(cga.get_stats())
        #cga.write_cycles()
        #cga.render_callgraph()


    df = pandas.DataFrame(data, columns = headers, index = idx)
    print(df)


if __name__== "__main__":
    parser = argparse.ArgumentParser(\
            description='Read call trace file and generate call graph.')
    parser.add_argument('outdir',
            type=str, help='root dir of output files.')
    parser.add_argument('-r', '--root', type=str, default='main',
            help='name of root node (default=main).')
    args = parser.parse_args()

    main(args)
