#!/bin/python
import sys
import os
import os.path
import pygraph.readwrite.dot
from sets import Set
import utils
    
    
def main(inf, outf):

    fout = open(outf, 'w')
    
    ############################
    # Parse dot file and remove back edges
    ############################
    fout.write('[%s] parsing ... dot file\n' % (inf))
    fout.flush()
    g = pygraph.readwrite.dot.read_dot_file(inf)
    fout.write('[%s] removing back edges ... dot file\n' %(inf))
    fout.flush()
    utils.remove_backedge(g)
    #utils.remove_backedge(g, u'A')

    ############################
    # using num_ss_allpaths
    ############################
    paths = utils.num_ss_allpaths(g, inf, fout)
    ##paths = utils.num_ss_allpaths(g, inf, fout, u'A')
    MaxID = 0
    for node, list in paths.iteritems():
        MaxID += len(list)
    fout.write('[%s] MaxID: %d\n' % (inf, MaxID-1))
    
    ############################
    # using num_ss_allpaths2
    ############################
    ##paths = utils.num_ss_allpaths2(g, inf, fout)
    #MaxID = utils.num_ss_allpaths2(g, inf, fout, u'A')
    #fout.write('[%s] MaxID: %d\n' % (inf, MaxID-1))

    fout.close()



if __name__== "__main__":
    if len(sys.argv) != 3:
        print("usage: %s dot_file output" % (sys.argv[0]))
        exit(1)

    main(sys.argv[1], sys.argv[2])
