#!/usr/bin/python
import sys
import os
import os.path
import argparse
import utils
from graphviz import Digraph
from callgraph import callgraph as callgraph
from callgraph import pccegraph as pccegraph
from dcce import dcce as dcce
import pcce


def write_cc_file(args, cg, maxid, node2id):
    f = open(args.cc_file, 'w')
    for caller, (callee, callsite) in cg.edges():
        wt = cg.edge_weight((caller,callee,callsite))
        #if wt == 0:
        #    wt = maxid+1
        f.write('%d-%s:%d-%s:%s:%d\n' %(int(node2id[caller]), caller, int(node2id[callee]), callee, callsite, wt))
    f.close()

def write_numcc_file(args, cg, node2id):
    f = open(args.numcc_file, 'w')
    for n in cg.nodes():
        f.write('%d-%s:%d\n' %(int(node2id[n]), n, cg.getnumCC(n)))
    f.close()

def write_backedge_file(args, backedge):
    f = open(args.backedge_file, 'w')
    for s in backedge:
        f.write(s+'\n')
    f.close()

def write_funcptr_file(args, cg):
    # callsite -> caller -> [callees]
    cs2caller2callees = {}
    for caller, (callee, callsite) in cg.edges():
        if callsite not in cs2caller2callees:
            cs2caller2callees[callsite] = {}

        if caller not in cs2caller2callees[callsite]:
            cs2caller2callees[callsite][caller] = []
        assert(len(cs2caller2callees[callsite].keys()) == 1)

        cs2caller2callees[callsite][caller].append(callee)

    f = open(args.funcptr_file, 'w')
    for callsite, caller2callees in cs2caller2callees.items():
        for caller, callees in caller2callees.items():
            ncallees = len(callees)
            if ncallees > 1:
                f.write("%s : %d\n" % (callsite, ncallees))

    f.close()

def write_stats_file(args, c_maxid, c_backedge_id, \
        max_neighbors, max_neighbors_name, mn_maxid, \
        max_incidents, max_incidents_name, mi_maxid):
    f = open(args.stats_file, 'w')
    f.write('%d %d %d %s %d %d %s %d\n' % \
            (c_maxid, c_backedge_id, \
            max_neighbors, max_neighbors_name, mn_maxid, \
            max_incidents, max_incidents_name, mi_maxid))
    f.close()

def write_connectivity(args, connectivity):
    f = open(args.conn_file, 'w')
    for n, (nn, ni) in connectivity.iteritems():
        f.write("%s:%d,%d\n" % (n, nn, ni))


def render_callgraph(cg, args, maxids):
    dot = Digraph()
    for node in cg.nodes():
        dot.node(node, label=node+':'+str(maxids[node]))

    for caller, (callee, callsite) in cg.edges():
        wt = cg.edge_weight((caller,callee,callsite))
        dot.edge(caller, callee,
                label=callsite+':'+str(wt))

    ## create dot file and render it
    dot.save(args.dotfile)
    dot.render(args.dotfile, view=args.show)

def main(args):

    c_cg, node2id = utils.make_callgraph(args.trace, args.scheme, args.root)
    if args.scheme == 'dcce':
        print("dcce")
        ## caculate maxid of cc encoding
        c_encode = dcce()
        c_maxids, c_backedge, c_backedge_id, \
                max_neighbors, max_neighbors_name, mn_maxid, \
                max_incidents, max_incidents_name, mi_maxid, \
                connectivity \
                = c_encode.maxid(c_cg, args.root)
        print ('[%s] num_node       %d' % (args.bench, len(c_cg.nodes())))
        print ('[%s] num_callsite   %d' % (args.bench, len(c_cg.edges())))
        print ('[%s] maxid is       %d' % (args.bench, c_maxids[args.root]))
        print ('[%s] backedge_id is %d' % (args.bench, c_backedge_id))
        print ('[%s] max_neighbors is %d' % (args.bench, max_neighbors))
        print ('[%s] mn_maxid is %d' % (args.bench, mn_maxid))
        print ('[%s] max_incidents is %d' % (args.bench, max_incidents))
        print ('[%s] mi_maxid is %d' % (args.bench, mi_maxid))
        sys.stdout.flush()
        #render_callgraph(c_cg, args, c_maxids)
        write_cc_file(args, c_cg, c_maxids[args.root], node2id)
        write_stats_file(args, c_maxids[args.root]+c_backedge_id, c_backedge_id, \
                max_neighbors, max_neighbors_name, mn_maxid, \
                max_incidents, max_incidents_name, mi_maxid)
        write_connectivity(args, connectivity)
        write_backedge_file(args, c_backedge)
        write_funcptr_file(args, c_cg)
    else:
        print("pcce")
        c_encode = pcce.pcce(c_cg)
        c_encode.instrument(c_cg.nodes(), c_cg.edges())
        write_cc_file(args, c_cg, 0, node2id)
        write_numcc_file(args, c_cg, node2id)
        #render_callgraph(c_cg, args, c_maxids)



if __name__== "__main__":
    parser = argparse.ArgumentParser(\
            description='Read call trace file and generate call graph.')
    parser.add_argument('trace',
            type=str, help='input file of function call trace.')
    parser.add_argument('dotfile',
            type=str, help='output file of dotfile.')
    parser.add_argument('cc_file',
            type=str, help='output file of calling context.')
    parser.add_argument('numcc_file',
            type=str, help='output file of number of calling context.')
    parser.add_argument('stats_file',
            type=str, help='output file of statistics.')
    parser.add_argument('conn_file',
            type=str, help='output file of connectivity.')
    parser.add_argument('backedge_file',
            type=str, help='output file of backedges.')
    parser.add_argument('funcptr_file',
            type=str, help='output file of funcptr.')
    parser.add_argument('bench',
            type=str, help='name of benchmark.')
    parser.add_argument('root',
            type=str, help='start node of the callgraph(ex. main)')
    parser.add_argument('scheme',
            type=str, help='scheme(dcce/pcce)')
    parser.add_argument('-s',
            '--show', action='store_true', help='display rendered graph.')

    args = parser.parse_args()

    main(args)
