import argparse
import os
import pandas

benches = [
    '600.perlbench_s', # cannot run instrument because of integer overflow
    #'602.gcc_s',      # compile issue
    '605.mcf_s',
    #'607.cactuBSSN_s',# compile issue
    '619.lbm_s',
    '620.omnetpp_s',  # assertion during dump-callgraph lineno: 356
    '623.xalancbmk_s',# assertion during dump-callgraph lineno: 356
    '625.x264_s',
    '631.deepsjeng_s',
    '638.imagick_s',
    '641.leela_s',   # assertion during dump-callgraph lineno: 356
    '644.nab_s',
    '657.xz_s',
    '998.specrand_is',
    '100.test',
    ]

output_root = '../output/dcce/ccenc/'


def get_ncycles(bench):
    file = '%s/%s.backedge' % (output_root, bench)
    nlines = 0
    with open(file, 'r') as f:
        for line in f:
            nlines += 1
    return nlines

def get_nfptr_maxjmps(bench):
    file = '%s/%s.funcptr' % (output_root, bench)
    nlines = 0
    max_jmps = 0
    with open(file, 'r') as f:
        for line in f:
            nlines += 1
            n_jmps = int(line.strip().split(':')[1].strip())
            if n_jmps > max_jmps:
                max_jmps = n_jmps
    return nlines, max_jmps

def get_num_callsite(bench):
    file = '%s/%s.cc' % (output_root, bench)
    nlines = 0
    with open(file, 'r') as f:
        for line in f:
            nlines += 1
    return nlines

def read_stat_files(bench):
    file = '%s/%s.stats' % (output_root, bench)
    
    with open(file, 'r') as f:
        line = f.readline()
    return line.strip().split(' ')


def collect_stats(bench):
    maxccid, backedge_id, \
            max_neighbors, max_neighbors_name, mn_maxid, \
            max_incidents, max_incidents_name, mi_maxid  = read_stat_files(bench)
    n_cycles = get_ncycles(bench)
    n_fptr, n_jmp_tgt = get_nfptr_maxjmps(bench)
    n_callsites = get_num_callsite(bench)
    #max_neighbors = get_max_neighbors(bench)

    return [maxccid, backedge_id, \
            n_callsites, n_cycles, n_fptr, n_jmp_tgt, \
            max_neighbors, max_neighbors_name, mn_maxid, \
            max_incidents, max_incidents_name, mi_maxid]



def main(args):
    headers = ['MaxCCID', 'backedge_id', \
            '# callsites', '# Cycles', '# FuncPtr', 'Max Jump Tgts', \
            'Max Neighbors', 'Max Neighbors Name', 'MN MaxID', \
            'Max Incidents', 'Max Incidents Name', 'MI MaxID']
    idx = []
    data = []
    if args.bench == 'all':
        for bench in benches:
            idx.append(bench)
            data.append(collect_stats(bench))
    else:
        idx.append(args.bench)
        data.append(collect_stats(args.bench))
    df = pandas.DataFrame(data, columns = headers, index= idx)
    print(df)



if __name__== "__main__":
    parser = argparse.ArgumentParser(\
            description="A program to plot stats generated by cc_encoder")

    parser.add_argument('--bench',
            type=str,
            help='benchmark name')
    
    parser.add_argument('--output',
            type=str,
            help='output path')

    args = parser.parse_args()
    main(args)
